baseurl = "https://blog.piotryordanov.com"
title = "Piotr Yordanov"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Piotr Yordanov"
  info = "üßô‚Äç‚ôÇÔ∏è Harry Piotr of Awesomness üßò‚Äç‚ôÇÔ∏è"
  description = "üßô‚Äç‚ôÇÔ∏è Harry Piotr of Awesomness üßò‚Äç‚ôÇÔ∏è"
  keywords = "blog,developer,personal"
  #avatarurl = "images/avatar.jpg"
  gravatar = "piotr.yordanov@gmail.com"

  favicon_32 = "/img/flatiron.svg"
  favicon_12 = "/img/flatiron.svg"

  since = ""

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = []
  customSCSS = []
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/piotryordanov/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/piotr-yordanov/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
